#%RAML 1.0
title: publish2Exchange
version: v1
baseUri: https://api.coppel.com/publish2Exchange
mediaType: application/json

/hello:
  get:
    description: Devuelve un saludo simple.
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
            example:
              message: "Publish GitActions with Exchange v1.0.0"
