name: Publish to Exchange + Home
on:
  push:
    branches: [develop]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Anypoint CLI
        uses: mulesoft/anypoint-cli-actions@v1
        with:
          version: 'latest'

      - name: Login Anypoint CLI
        run: anypoint-cli account login --username ${{ secrets.ANYPOINT_USERNAME }} --password ${{ secrets.ANYPOINT_PASSWORD }}

      - name: Publish RAML
        run: |
          anypoint-cli exchange:asset:upload publish2Exchange com.example/publish2Exchange/1.1.3 --type rest-api --file apispec.zip

      - name: Publish Home.md
        run: |
          anypoint-cli exchange:asset:page:upload com.example/publish2Exchange/1.1.3 home home.md
